name: info-dynamics
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  
  # Core scientific computing
  - numpy>=1.24.0
  - pandas>=2.0.0
  - scipy>=1.10.0
  
  # Statistics and machine learning
  - scikit-learn>=1.3.0
  - statsmodels>=0.14.0
  
  # Visualization
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - plotly>=5.15.0
  
  # Data processing
  - openpyxl>=3.1.0
  - xlrd>=2.0.0
  
  # Natural language processing (for transformation analysis)
  - nltk>=3.8
  - spacy>=3.6.0
  - transformers>=4.30.0
  - sentence-transformers>=2.2.0
  
  # Network analysis (for social media data)
  - networkx>=3.1
  - igraph>=0.10.0
  
  # Jupyter environment
  - jupyter>=1.0.0
  - jupyterlab>=4.0.0
  - ipywidgets>=8.0.0
  
  # Development tools
  - pytest>=7.4.0
  - black>=23.0.0
  - flake8>=6.0.0
  
  # Additional analysis tools
  - pingouin>=0.5.3  # Advanced statistical functions
  - factor_analyzer>=0.4.1  # Factor analysis
  
  # pip dependencies
  - pip
  - pip:
    - torch>=2.0.0  # PyTorch for deep learning models
    - datasets>=2.14.0  # Hugging Face datasets
    - wandb>=0.15.0  # Experiment tracking
    - umap-learn>=0.5.3  # Dimensionality reduction
    - hdbscan>=0.8.29  # Clustering
    - pymc>=5.7.0  # Bayesian modeling
    - arviz>=0.16.0  # Bayesian analysis visualization 